language: elixir
elixir:
  - 1.3
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - 1.8
otp_release:
  - 18.0
  - 19.0
  - 20.0
  - 21.0

matrix:
  exclude:
    - elixir: 1.3
      otp_release: 21.0
    - elixir: 1.4
      otp_release: 21.0
    - elixir: 1.5
      otp_release: 21.0
    - elixir: 1.3
      otp_release: 20.0
    - elixir: 1.6
      otp_release: 18.0
    - elixir: 1.7
      otp_release: 18.0
    - elixir: 1.8
      otp_release: 18.0
    - elixir: 1.8
      otp_release: 19.0
  include:
    elixir: 1.8
    otp_release: 21.0
    install: skip
    script: mix format --check-formatted --dry-run

script: mix coveralls.json
after_script:
  - bash <(curl -s https://codecov.io/bash)
